security.jwt.token.secret-key: sEcreTJWT12345=

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testwebdm
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update